title: Penrose Development
description: Software Engineering
baseurl: https://penrose.dev
permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js